In [5]:
# Benchmark: measuring runtime versus # iterations

In [6]:
#imports
import os, time, datetime, json, yaml
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
%load_ext autoreload
%autoreload 2
np.warnings.filterwarnings('ignore')

#excursion package imports
import excursion.test_suite.test_functions.fast_2D as testcase_2D

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
file = open('../excursion/test_suite/algorithm_options/algorithm_specs_2d_bench.yaml', "r")
algorithm_opts = yaml.safe_load(file)
print('algorithm_opts =')
print(json.dumps(algorithm_opts, indent=4))

from excursion.learner import Learner
learner = Learner(testcase_2D, algorithm_opts)

updates = range(10, 40, 1)


algorithm_opts =
{
    "example": "Simple Learner Usage",
    "ninit": 2,
    "init_type": "random",
    "jump_start": true,
    "device": "cpu",
    "likelihood": {
        "likelihood_type": "GaussianLikelihood",
        "epsilon": 0.0
    },
    "model": {
        "type": "ExactGP",
        "fit_optimizer": "Adam"
    },
    "acq": {
        "acq_type": "pes"
    }
}
Accuracy % 0.37


In [8]:
means = []
stdev = []
for n in updates:
    runs = []
    for run in range(1):
        learner = Learner(testcase_2D, algorithm_opts)


        start_time = time.process_time()

        n_updates = n
        #save results in folder
        # timestampStr = datetime.datetime.now().strftime('%d-%b-%Y_%H_%M_%S') + '\\'
        # outputfolder = r'C:\Users\excursion\Documents\excursion_project\excursion\examples\results'
        # outputfolder = os.path.join(outputfolder, timestampStr)
        # os.makedirs(outputfolder)

        for iteration in range(n_updates):
            new_x = learner.suggest()
            print(new_x)
            result = learner.evaluate_and_tell(new_x)

        #save results
        end_time = time.process_time() - start_time

        # estimator.print_results(outputfolder, testcase_details, algorithm_opts)


        runs.append(end_time)

    runs = pd.Series(runs)
    stdev.append(runs.std(ddof=0))
    means.append(runs.mean())

Accuracy % 0.57
tensor([[1., 1.]], dtype=torch.float64)
Accuracy % 0.65
tensor([[0.3333, 1.5000]], dtype=torch.float64)
Accuracy % 0.78
tensor([[1.3333, 0.8333]], dtype=torch.float64)
Accuracy % 0.88
tensor([[1.1667, 0.1667]], dtype=torch.float64)
Accuracy % 0.91
tensor([[0.3333, 1.0000]], dtype=torch.float64)
Accuracy % 0.9
tensor([[0.8333, 0.6667]], dtype=torch.float64)
Accuracy % 0.95
tensor([[0.6667, 0.8333]], dtype=torch.float64)
Accuracy % 0.96
tensor([[0.3333, 0.6667]], dtype=torch.float64)
Accuracy % 0.96
tensor([[0.0000, 0.6667]], dtype=torch.float64)
Accuracy % 0.97
tensor([[1.1667, 0.6667]], dtype=torch.float64)
Accuracy % 0.98
Accuracy % 0.64
tensor([[1.5000, 0.1667]], dtype=torch.float64)
Accuracy % 0.64
tensor([[1.3333, 0.5000]], dtype=torch.float64)
Accuracy % 0.64
tensor([[1.1667, 0.6667]], dtype=torch.float64)
Accuracy % 0.65
tensor([[0.8333, 0.5000]], dtype=torch.float64)
Accuracy % 0.85
tensor([[1.1667, 0.3333]], dtype=torch.float64)
Accuracy % 0.75
tensor([[0.1667, 

KeyboardInterrupt: 