In [5]:
from excursion import ExcursionProblem
import excursion.optimize as optimize
import numpy as np
import scipy.stats
np.warnings.filterwarnings('ignore')

In [6]:
N_UPDATES = 10
N_BATCH = 2

def expensive_func(X):
    return np.atleast_1d(scipy.stats.multivariate_normal.pdf(X,mean = [0.5,0.5], cov = np.diag([0.2,0.3])))

scandetails = ExcursionProblem([expensive_func], ndim = 2)
X,y_list,gps = optimize.init(scandetails)
for index in range(N_UPDATES):
    print('next')
    newX = optimize.suggest(gps, X, scandetails, batchsize=N_BATCH)
    print(newX)
    X,y_list,gps  = optimize.evaluate_and_refine(X,y_list,newX,scandetails)

next
[[0.94444323 0.83734469]
 [0.99626529 0.00815435]]
next
[[0.06118467 0.07150192]
 [0.99501515 0.47561099]]
next
[[0.55358371 0.20446804]
 [0.3183391  0.12528746]]
next
[[0.0966506  0.68114111]
 [0.44904663 0.16199749]]
next
[[0.105945   0.67212826]
 [0.58216149 0.22106836]]
next
[[0.34449215 0.1374408 ]
 [0.4141987  0.14892231]]
next
[[0.55933555 0.19110667]
 [0.45785126 0.17116225]]
next
[[0.38409315 0.14655503]
 [0.4326694  0.15791352]]
next
[[0.33997984 0.13366006]
 [0.12313822 0.67326342]]
next
[[0.4901915  0.16077279]
 [0.5223449  0.1770531 ]]
