In [1]:
import torch

from excursion_new.learner import Learner
import excursion_new.test_suite.test_functions.fast_2D as testcase_2D
import excursion_new.test_suite.test_functions.fast_1D as testcase_1D

learner_one = Learner(testcase_1D)
learner_two = Learner(testcase_2D)
learner_one.initialize()
learner_two.initialize()

C:\Users\excursion\anaconda3\envs\jason_refactor\lib\site-packages\numpy\lib\index_tricks.py:185: ComplexWarning: Casting complex values to real discards the imaginary part
  nn[k] = (nn[k]*step+start)


In [2]:
for iteration in range(2):
    x_one = learner_one.suggest()
    x_two = learner_two.suggest()
    print(x_two)
    print(x_one)
    learner_one.evaluate_and_tell(x_one)
    learner_two.evaluate_and_tell(x_two)

tensor([[0.3375, 1.0125]], device='cuda:0', dtype=torch.float64)
tensor([[0.2727]], device='cuda:0', dtype=torch.float64)
tensor([[0.1875, 0.8250]], device='cuda:0', dtype=torch.float64)
tensor([[-0.5152]], device='cuda:0', dtype=torch.float64)


C:\Users\excursion\anaconda3\envs\jason_refactor\lib\site-packages\gpytorch\likelihoods\gaussian_likelihood.py:270: GPInputWarning: You have passed data through a FixedNoiseGaussianLikelihood that did not match the size of the fixed noise, *and* you did not specify noise. This is treated as a no-op.
  warnings.warn(


In [3]:
import excursion_new.test_suite.test_functions.fast_3D as testcase_3D
learner_three = Learner(testcase_3D)
learner_three.initialize()

In [4]:
for iteration in range(2):
    x_three = learner_three.suggest()
    print(x_three)
    learner_three.evaluate_and_tell(x_three)

tensor([[0.3750, 0.3375, 0.1875]], device='cuda:0', dtype=torch.float64)
tensor([[1.4625, 0.7500, 0.9375]], device='cuda:0', dtype=torch.float64)
